trigger:
  - develop
  - merge

variables:
  major: '0'
  minor: '0'
  patch: '1'
  version: $(major).$(minor).$(patch)

stages:
  - stage: UI
    displayName: "Build and publish UI"
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: BuildWebApp
        timeoutInMinutes: 20
        workspace:
          clean: all
        steps:
        - task: NodeTool@0
          displayName: 'Install Node.js'
          inputs:
            versionSpec: '20.x'

        - script: |
            npm install -g @angular/cli
            npm install
            ng build --prod -op $(Build.ArtifactStagingDirectory)
          displayName: 'npm install and build'

        - task: PublishBuildArtifacts@1
          displayName: "Publishing UI"
          condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            publishLocation: Container
            ArtifactName: 'UI'
